# This example uses YAML anchors which allows reuse of multiple keys 
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/master/nixos/.sops.yaml
# for a more complex example.
keys:
  - &seneca age1nklf7xdd6uz5xlpt49qgem3tpcyqhcj6e4k4nav3fn07muvvcscskfmz3r
    #  - &host_hullen 
creation_rules:
  - path_regex: hosts/seneca/secrets.yaml$
    key_groups:
    - age:
        - *seneca
  - path_regex: hosts/common/secrets.yaml$
    key_groups:
    - age:
        - *seneca
