#!/bin/bash

host="${1:-$(hostname)}"

git add -A
git diff -U0 *.nix
echo "NixOS Rebuilding ..."
sudo nixos-rebuild switch --flake .#${host} &>nixos-switch.log || (
  cat nixos-switch.log | grep --color error && false)
gen=$(nixos-rebuild list-generations | grep current)
git commit -am "$gen"
